FROM docker.1ms.run/opensearchproject/opensearch:latest

RUN /usr/share/opensearch/bin/opensearch-plugin install -b https://release.infinilabs.com/analysis-ik/stable/opensearch-analysis-ik-2.18.0.zip

