FROM elasticsearch:7.6.1

MAINTAINER hnliuwx@gmail.com

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install -b  https://release.infinilabs.com/analysis-ik/stable/elasticsearch-analysis-ik-7.6.1.zip

